package com.heroku.mapper;

import com.heroku.entity.Alltags;
import com.heroku.entity.AlltagsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlltagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alltags
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int countByExample(AlltagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alltags
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int deleteByExample(AlltagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alltags
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int deleteByPrimaryKey(Integer alltagsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alltags
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int insert(Alltags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alltags
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int insertSelective(Alltags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alltags
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    List<Alltags> selectByExample(AlltagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alltags
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    Alltags selectByPrimaryKey(Integer alltagsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alltags
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int updateByExampleSelective(@Param("record") Alltags record, @Param("example") AlltagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alltags
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int updateByExample(@Param("record") Alltags record, @Param("example") AlltagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alltags
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int updateByPrimaryKeySelective(Alltags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alltags
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int updateByPrimaryKey(Alltags record);
}