package com.heroku.mapper;

import com.heroku.entity.ASelectTail;
import com.heroku.entity.ASelectTailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ASelectTailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_select_tail
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int countByExample(ASelectTailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_select_tail
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int deleteByExample(ASelectTailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_select_tail
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int insert(ASelectTail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_select_tail
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int insertSelective(ASelectTail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_select_tail
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    List<ASelectTail> selectByExample(ASelectTailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_select_tail
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int updateByExampleSelective(@Param("record") ASelectTail record, @Param("example") ASelectTailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_select_tail
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int updateByExample(@Param("record") ASelectTail record, @Param("example") ASelectTailExample example);
}