package com.heroku.mapper;

import com.heroku.entity.ATag;
import com.heroku.entity.ATagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ATagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int countByExample(ATagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int deleteByExample(ATagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int deleteByPrimaryKey(String tagname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int insert(ATag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int insertSelective(ATag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    List<ATag> selectByExample(ATagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    ATag selectByPrimaryKey(String tagname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int updateByExampleSelective(@Param("record") ATag record, @Param("example") ATagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int updateByExample(@Param("record") ATag record, @Param("example") ATagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int updateByPrimaryKeySelective(ATag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.a_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int updateByPrimaryKey(ATag record);
}