package com.heroku.mapper;

import com.heroku.entity.BTag;
import com.heroku.entity.BTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int countByExample(BTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int deleteByExample(BTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int deleteByPrimaryKey(String bTagname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int insert(BTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int insertSelective(BTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    List<BTag> selectByExampleWithBLOBs(BTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    List<BTag> selectByExample(BTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    BTag selectByPrimaryKey(String bTagname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int updateByExampleSelective(@Param("record") BTag record, @Param("example") BTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") BTag record, @Param("example") BTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int updateByExample(@Param("record") BTag record, @Param("example") BTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int updateByPrimaryKeySelective(BTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(BTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    int updateByPrimaryKey(BTag record);
}