package com.heroku.mapper;

import com.heroku.entity.Imgsave;
import com.heroku.entity.ImgsaveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImgsaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.imgsave
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    int countByExample(ImgsaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.imgsave
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    int deleteByExample(ImgsaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.imgsave
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.imgsave
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    int insert(Imgsave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.imgsave
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    int insertSelective(Imgsave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.imgsave
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    List<Imgsave> selectByExampleWithBLOBs(ImgsaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.imgsave
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    List<Imgsave> selectByExample(ImgsaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.imgsave
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    Imgsave selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.imgsave
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") Imgsave record, @Param("example") ImgsaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.imgsave
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Imgsave record, @Param("example") ImgsaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.imgsave
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    int updateByExample(@Param("record") Imgsave record, @Param("example") ImgsaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.imgsave
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    int updateByPrimaryKeySelective(Imgsave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.imgsave
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Imgsave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.imgsave
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    int updateByPrimaryKey(Imgsave record);
}