package com.heroku.entity;

import java.io.Serializable;
import java.util.Date;

public class Alltags implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.alltags.alltagsid
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private Integer alltagsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.alltags.alltagsname
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private String alltagsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.alltags.createtime
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.alltags.uptime
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private Date uptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.alltags
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.alltags.alltagsid
     *
     * @return the value of public.alltags.alltagsid
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public Integer getAlltagsid() {
        return alltagsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.alltags.alltagsid
     *
     * @param alltagsid the value for public.alltags.alltagsid
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setAlltagsid(Integer alltagsid) {
        this.alltagsid = alltagsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.alltags.alltagsname
     *
     * @return the value of public.alltags.alltagsname
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public String getAlltagsname() {
        return alltagsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.alltags.alltagsname
     *
     * @param alltagsname the value for public.alltags.alltagsname
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setAlltagsname(String alltagsname) {
        this.alltagsname = alltagsname == null ? null : alltagsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.alltags.createtime
     *
     * @return the value of public.alltags.createtime
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.alltags.createtime
     *
     * @param createtime the value for public.alltags.createtime
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.alltags.uptime
     *
     * @return the value of public.alltags.uptime
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public Date getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.alltags.uptime
     *
     * @param uptime the value for public.alltags.uptime
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setUptime(Date uptime) {
        this.uptime = uptime;
    }
}