package com.heroku.entity;

import java.io.Serializable;

public class ASelectTail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.a_select_tail.a_select_tname
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private String aSelectTname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.a_select_tail.a_select_tvalue
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private String aSelectTvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.a_select_tail
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.a_select_tail.a_select_tname
     *
     * @return the value of public.a_select_tail.a_select_tname
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public String getaSelectTname() {
        return aSelectTname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.a_select_tail.a_select_tname
     *
     * @param aSelectTname the value for public.a_select_tail.a_select_tname
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setaSelectTname(String aSelectTname) {
        this.aSelectTname = aSelectTname == null ? null : aSelectTname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.a_select_tail.a_select_tvalue
     *
     * @return the value of public.a_select_tail.a_select_tvalue
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public String getaSelectTvalue() {
        return aSelectTvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.a_select_tail.a_select_tvalue
     *
     * @param aSelectTvalue the value for public.a_select_tail.a_select_tvalue
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setaSelectTvalue(String aSelectTvalue) {
        this.aSelectTvalue = aSelectTvalue == null ? null : aSelectTvalue.trim();
    }
}