package com.heroku.entity;

import java.io.Serializable;

public class ASelect implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.a_select.a_select_id
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private Integer aSelectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.a_select.a_select_name
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private String aSelectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.a_select
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.a_select.a_select_id
     *
     * @return the value of public.a_select.a_select_id
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public Integer getaSelectId() {
        return aSelectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.a_select.a_select_id
     *
     * @param aSelectId the value for public.a_select.a_select_id
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setaSelectId(Integer aSelectId) {
        this.aSelectId = aSelectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.a_select.a_select_name
     *
     * @return the value of public.a_select.a_select_name
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public String getaSelectName() {
        return aSelectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.a_select.a_select_name
     *
     * @param aSelectName the value for public.a_select.a_select_name
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setaSelectName(String aSelectName) {
        this.aSelectName = aSelectName == null ? null : aSelectName.trim();
    }
}