package com.heroku.entity;

import java.io.Serializable;
import java.util.Date;

public class ATag implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.a_tag.tagname
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private String tagname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.a_tag.tagtype
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private String tagtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.a_tag.tagvalue
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private String tagvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.a_tag.tagvalues
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private Object tagvalues;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.a_tag.alltagsid
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private Integer alltagsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.a_tag.lastuptime
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private Date lastuptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.a_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.a_tag.tagname
     *
     * @return the value of public.a_tag.tagname
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public String getTagname() {
        return tagname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.a_tag.tagname
     *
     * @param tagname the value for public.a_tag.tagname
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setTagname(String tagname) {
        this.tagname = tagname == null ? null : tagname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.a_tag.tagtype
     *
     * @return the value of public.a_tag.tagtype
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public String getTagtype() {
        return tagtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.a_tag.tagtype
     *
     * @param tagtype the value for public.a_tag.tagtype
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setTagtype(String tagtype) {
        this.tagtype = tagtype == null ? null : tagtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.a_tag.tagvalue
     *
     * @return the value of public.a_tag.tagvalue
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public String getTagvalue() {
        return tagvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.a_tag.tagvalue
     *
     * @param tagvalue the value for public.a_tag.tagvalue
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setTagvalue(String tagvalue) {
        this.tagvalue = tagvalue == null ? null : tagvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.a_tag.tagvalues
     *
     * @return the value of public.a_tag.tagvalues
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public Object getTagvalues() {
        return tagvalues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.a_tag.tagvalues
     *
     * @param tagvalues the value for public.a_tag.tagvalues
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setTagvalues(Object tagvalues) {
        this.tagvalues = tagvalues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.a_tag.alltagsid
     *
     * @return the value of public.a_tag.alltagsid
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public Integer getAlltagsid() {
        return alltagsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.a_tag.alltagsid
     *
     * @param alltagsid the value for public.a_tag.alltagsid
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setAlltagsid(Integer alltagsid) {
        this.alltagsid = alltagsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.a_tag.lastuptime
     *
     * @return the value of public.a_tag.lastuptime
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public Date getLastuptime() {
        return lastuptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.a_tag.lastuptime
     *
     * @param lastuptime the value for public.a_tag.lastuptime
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setLastuptime(Date lastuptime) {
        this.lastuptime = lastuptime;
    }
}