package com.heroku.entity;

import java.util.ArrayList;
import java.util.List;

public class BTagExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public BTagExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBTagnameIsNull() {
            addCriterion("b_tagname is null");
            return (Criteria) this;
        }

        public Criteria andBTagnameIsNotNull() {
            addCriterion("b_tagname is not null");
            return (Criteria) this;
        }

        public Criteria andBTagnameEqualTo(String value) {
            addCriterion("b_tagname =", value, "bTagname");
            return (Criteria) this;
        }

        public Criteria andBTagnameNotEqualTo(String value) {
            addCriterion("b_tagname <>", value, "bTagname");
            return (Criteria) this;
        }

        public Criteria andBTagnameGreaterThan(String value) {
            addCriterion("b_tagname >", value, "bTagname");
            return (Criteria) this;
        }

        public Criteria andBTagnameGreaterThanOrEqualTo(String value) {
            addCriterion("b_tagname >=", value, "bTagname");
            return (Criteria) this;
        }

        public Criteria andBTagnameLessThan(String value) {
            addCriterion("b_tagname <", value, "bTagname");
            return (Criteria) this;
        }

        public Criteria andBTagnameLessThanOrEqualTo(String value) {
            addCriterion("b_tagname <=", value, "bTagname");
            return (Criteria) this;
        }

        public Criteria andBTagnameLike(String value) {
            addCriterion("b_tagname like", value, "bTagname");
            return (Criteria) this;
        }

        public Criteria andBTagnameNotLike(String value) {
            addCriterion("b_tagname not like", value, "bTagname");
            return (Criteria) this;
        }

        public Criteria andBTagnameIn(List<String> values) {
            addCriterion("b_tagname in", values, "bTagname");
            return (Criteria) this;
        }

        public Criteria andBTagnameNotIn(List<String> values) {
            addCriterion("b_tagname not in", values, "bTagname");
            return (Criteria) this;
        }

        public Criteria andBTagnameBetween(String value1, String value2) {
            addCriterion("b_tagname between", value1, value2, "bTagname");
            return (Criteria) this;
        }

        public Criteria andBTagnameNotBetween(String value1, String value2) {
            addCriterion("b_tagname not between", value1, value2, "bTagname");
            return (Criteria) this;
        }

        public Criteria andBTvalueIsNull() {
            addCriterion("b_tvalue is null");
            return (Criteria) this;
        }

        public Criteria andBTvalueIsNotNull() {
            addCriterion("b_tvalue is not null");
            return (Criteria) this;
        }

        public Criteria andBTvalueEqualTo(String value) {
            addCriterion("b_tvalue =", value, "bTvalue");
            return (Criteria) this;
        }

        public Criteria andBTvalueNotEqualTo(String value) {
            addCriterion("b_tvalue <>", value, "bTvalue");
            return (Criteria) this;
        }

        public Criteria andBTvalueGreaterThan(String value) {
            addCriterion("b_tvalue >", value, "bTvalue");
            return (Criteria) this;
        }

        public Criteria andBTvalueGreaterThanOrEqualTo(String value) {
            addCriterion("b_tvalue >=", value, "bTvalue");
            return (Criteria) this;
        }

        public Criteria andBTvalueLessThan(String value) {
            addCriterion("b_tvalue <", value, "bTvalue");
            return (Criteria) this;
        }

        public Criteria andBTvalueLessThanOrEqualTo(String value) {
            addCriterion("b_tvalue <=", value, "bTvalue");
            return (Criteria) this;
        }

        public Criteria andBTvalueLike(String value) {
            addCriterion("b_tvalue like", value, "bTvalue");
            return (Criteria) this;
        }

        public Criteria andBTvalueNotLike(String value) {
            addCriterion("b_tvalue not like", value, "bTvalue");
            return (Criteria) this;
        }

        public Criteria andBTvalueIn(List<String> values) {
            addCriterion("b_tvalue in", values, "bTvalue");
            return (Criteria) this;
        }

        public Criteria andBTvalueNotIn(List<String> values) {
            addCriterion("b_tvalue not in", values, "bTvalue");
            return (Criteria) this;
        }

        public Criteria andBTvalueBetween(String value1, String value2) {
            addCriterion("b_tvalue between", value1, value2, "bTvalue");
            return (Criteria) this;
        }

        public Criteria andBTvalueNotBetween(String value1, String value2) {
            addCriterion("b_tvalue not between", value1, value2, "bTvalue");
            return (Criteria) this;
        }

        public Criteria andBSvalueIsNull() {
            addCriterion("b_svalue is null");
            return (Criteria) this;
        }

        public Criteria andBSvalueIsNotNull() {
            addCriterion("b_svalue is not null");
            return (Criteria) this;
        }

        public Criteria andBSvalueEqualTo(String value) {
            addCriterion("b_svalue =", value, "bSvalue");
            return (Criteria) this;
        }

        public Criteria andBSvalueNotEqualTo(String value) {
            addCriterion("b_svalue <>", value, "bSvalue");
            return (Criteria) this;
        }

        public Criteria andBSvalueGreaterThan(String value) {
            addCriterion("b_svalue >", value, "bSvalue");
            return (Criteria) this;
        }

        public Criteria andBSvalueGreaterThanOrEqualTo(String value) {
            addCriterion("b_svalue >=", value, "bSvalue");
            return (Criteria) this;
        }

        public Criteria andBSvalueLessThan(String value) {
            addCriterion("b_svalue <", value, "bSvalue");
            return (Criteria) this;
        }

        public Criteria andBSvalueLessThanOrEqualTo(String value) {
            addCriterion("b_svalue <=", value, "bSvalue");
            return (Criteria) this;
        }

        public Criteria andBSvalueLike(String value) {
            addCriterion("b_svalue like", value, "bSvalue");
            return (Criteria) this;
        }

        public Criteria andBSvalueNotLike(String value) {
            addCriterion("b_svalue not like", value, "bSvalue");
            return (Criteria) this;
        }

        public Criteria andBSvalueIn(List<String> values) {
            addCriterion("b_svalue in", values, "bSvalue");
            return (Criteria) this;
        }

        public Criteria andBSvalueNotIn(List<String> values) {
            addCriterion("b_svalue not in", values, "bSvalue");
            return (Criteria) this;
        }

        public Criteria andBSvalueBetween(String value1, String value2) {
            addCriterion("b_svalue between", value1, value2, "bSvalue");
            return (Criteria) this;
        }

        public Criteria andBSvalueNotBetween(String value1, String value2) {
            addCriterion("b_svalue not between", value1, value2, "bSvalue");
            return (Criteria) this;
        }

        public Criteria andBTypeIsNull() {
            addCriterion("b_type is null");
            return (Criteria) this;
        }

        public Criteria andBTypeIsNotNull() {
            addCriterion("b_type is not null");
            return (Criteria) this;
        }

        public Criteria andBTypeEqualTo(String value) {
            addCriterion("b_type =", value, "bType");
            return (Criteria) this;
        }

        public Criteria andBTypeNotEqualTo(String value) {
            addCriterion("b_type <>", value, "bType");
            return (Criteria) this;
        }

        public Criteria andBTypeGreaterThan(String value) {
            addCriterion("b_type >", value, "bType");
            return (Criteria) this;
        }

        public Criteria andBTypeGreaterThanOrEqualTo(String value) {
            addCriterion("b_type >=", value, "bType");
            return (Criteria) this;
        }

        public Criteria andBTypeLessThan(String value) {
            addCriterion("b_type <", value, "bType");
            return (Criteria) this;
        }

        public Criteria andBTypeLessThanOrEqualTo(String value) {
            addCriterion("b_type <=", value, "bType");
            return (Criteria) this;
        }

        public Criteria andBTypeLike(String value) {
            addCriterion("b_type like", value, "bType");
            return (Criteria) this;
        }

        public Criteria andBTypeNotLike(String value) {
            addCriterion("b_type not like", value, "bType");
            return (Criteria) this;
        }

        public Criteria andBTypeIn(List<String> values) {
            addCriterion("b_type in", values, "bType");
            return (Criteria) this;
        }

        public Criteria andBTypeNotIn(List<String> values) {
            addCriterion("b_type not in", values, "bType");
            return (Criteria) this;
        }

        public Criteria andBTypeBetween(String value1, String value2) {
            addCriterion("b_type between", value1, value2, "bType");
            return (Criteria) this;
        }

        public Criteria andBTypeNotBetween(String value1, String value2) {
            addCriterion("b_type not between", value1, value2, "bType");
            return (Criteria) this;
        }

        public Criteria andAlltagsidIsNull() {
            addCriterion("alltagsid is null");
            return (Criteria) this;
        }

        public Criteria andAlltagsidIsNotNull() {
            addCriterion("alltagsid is not null");
            return (Criteria) this;
        }

        public Criteria andAlltagsidEqualTo(Integer value) {
            addCriterion("alltagsid =", value, "alltagsid");
            return (Criteria) this;
        }

        public Criteria andAlltagsidNotEqualTo(Integer value) {
            addCriterion("alltagsid <>", value, "alltagsid");
            return (Criteria) this;
        }

        public Criteria andAlltagsidGreaterThan(Integer value) {
            addCriterion("alltagsid >", value, "alltagsid");
            return (Criteria) this;
        }

        public Criteria andAlltagsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("alltagsid >=", value, "alltagsid");
            return (Criteria) this;
        }

        public Criteria andAlltagsidLessThan(Integer value) {
            addCriterion("alltagsid <", value, "alltagsid");
            return (Criteria) this;
        }

        public Criteria andAlltagsidLessThanOrEqualTo(Integer value) {
            addCriterion("alltagsid <=", value, "alltagsid");
            return (Criteria) this;
        }

        public Criteria andAlltagsidIn(List<Integer> values) {
            addCriterion("alltagsid in", values, "alltagsid");
            return (Criteria) this;
        }

        public Criteria andAlltagsidNotIn(List<Integer> values) {
            addCriterion("alltagsid not in", values, "alltagsid");
            return (Criteria) this;
        }

        public Criteria andAlltagsidBetween(Integer value1, Integer value2) {
            addCriterion("alltagsid between", value1, value2, "alltagsid");
            return (Criteria) this;
        }

        public Criteria andAlltagsidNotBetween(Integer value1, Integer value2) {
            addCriterion("alltagsid not between", value1, value2, "alltagsid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.b_tag
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 03 13:57:53 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}