package com.heroku.entity;

import java.io.Serializable;

public class BTag implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.b_tag.b_tagname
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private String bTagname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.b_tag.b_tvalue
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private String bTvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.b_tag.b_svalue
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private String bSvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.b_tag.b_type
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private String bType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.b_tag.alltagsid
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private Integer alltagsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.b_tag.b_ivalue
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private byte[] bIvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.b_tag
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.b_tag.b_tagname
     *
     * @return the value of public.b_tag.b_tagname
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public String getbTagname() {
        return bTagname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.b_tag.b_tagname
     *
     * @param bTagname the value for public.b_tag.b_tagname
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setbTagname(String bTagname) {
        this.bTagname = bTagname == null ? null : bTagname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.b_tag.b_tvalue
     *
     * @return the value of public.b_tag.b_tvalue
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public String getbTvalue() {
        return bTvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.b_tag.b_tvalue
     *
     * @param bTvalue the value for public.b_tag.b_tvalue
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setbTvalue(String bTvalue) {
        this.bTvalue = bTvalue == null ? null : bTvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.b_tag.b_svalue
     *
     * @return the value of public.b_tag.b_svalue
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public String getbSvalue() {
        return bSvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.b_tag.b_svalue
     *
     * @param bSvalue the value for public.b_tag.b_svalue
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setbSvalue(String bSvalue) {
        this.bSvalue = bSvalue == null ? null : bSvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.b_tag.b_type
     *
     * @return the value of public.b_tag.b_type
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public String getbType() {
        return bType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.b_tag.b_type
     *
     * @param bType the value for public.b_tag.b_type
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setbType(String bType) {
        this.bType = bType == null ? null : bType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.b_tag.alltagsid
     *
     * @return the value of public.b_tag.alltagsid
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public Integer getAlltagsid() {
        return alltagsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.b_tag.alltagsid
     *
     * @param alltagsid the value for public.b_tag.alltagsid
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setAlltagsid(Integer alltagsid) {
        this.alltagsid = alltagsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.b_tag.b_ivalue
     *
     * @return the value of public.b_tag.b_ivalue
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public byte[] getbIvalue() {
        return bIvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.b_tag.b_ivalue
     *
     * @param bIvalue the value for public.b_tag.b_ivalue
     *
     * @mbggenerated Fri Nov 03 13:57:53 CST 2017
     */
    public void setbIvalue(byte[] bIvalue) {
        this.bIvalue = bIvalue;
    }
}