package com.heroku.entity;

import java.io.Serializable;

public class Imgsave implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.imgsave.username
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.imgsave.imgid
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    private Integer imgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.imgsave.longblob
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    private byte[] longblob;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.imgsave.username
     *
     * @return the value of public.imgsave.username
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.imgsave.username
     *
     * @param username the value for public.imgsave.username
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.imgsave.imgid
     *
     * @return the value of public.imgsave.imgid
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    public Integer getImgid() {
        return imgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.imgsave.imgid
     *
     * @param imgid the value for public.imgsave.imgid
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    public void setImgid(Integer imgid) {
        this.imgid = imgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.imgsave.longblob
     *
     * @return the value of public.imgsave.longblob
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    public byte[] getLongblob() {
        return longblob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.imgsave.longblob
     *
     * @param longblob the value for public.imgsave.longblob
     *
     * @mbggenerated Tue Oct 10 17:56:59 CST 2017
     */
    public void setLongblob(byte[] longblob) {
        this.longblob = longblob;
    }
}