package com.heroku.entity;

import java.io.Serializable;

public class URolePermission  implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.u_role_permission.rid
     *
     * @mbggenerated Thu Sep 28 11:55:48 CST 2017
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.u_role_permission.pid
     *
     * @mbggenerated Thu Sep 28 11:55:48 CST 2017
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.u_role_permission.rid
     *
     * @return the value of public.u_role_permission.rid
     *
     * @mbggenerated Thu Sep 28 11:55:48 CST 2017
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.u_role_permission.rid
     *
     * @param rid the value for public.u_role_permission.rid
     *
     * @mbggenerated Thu Sep 28 11:55:48 CST 2017
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.u_role_permission.pid
     *
     * @return the value of public.u_role_permission.pid
     *
     * @mbggenerated Thu Sep 28 11:55:48 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.u_role_permission.pid
     *
     * @param pid the value for public.u_role_permission.pid
     *
     * @mbggenerated Thu Sep 28 11:55:48 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}